# -*- coding: utf-8 -*-
"""day2-Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FU4b3U4mTzfC8gFcKPM_tpS1qYpBJJZE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

price = [48000,54000,57000,49000,47000,45000]
year = [2015,2016,2017,2018,2019,2020]

plt.plot(year,price)

batsman = pd.read_csv('/content/sharma-kohli.csv')
batsman

plt.plot(batsman['index'],batsman['V Kohli'])

plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])

plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.plot(batsman['index'],batsman['V Kohli'],color='black')
plt.plot(batsman['index'],batsman['RG Sharma'],color='green')

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.plot(batsman['index'],batsman['V Kohli'],color='black',linestyle='dashdot',linewidth=3)
plt.plot(batsman['index'],batsman['RG Sharma'],color='green',linestyle='dashdot',linewidth=8)

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.plot(batsman['index'],batsman['V Kohli'],color='black',linestyle='dashdot',linewidth=3,marker='D',markersize=10)
plt.plot(batsman['index'],batsman['RG Sharma'],color='green',linestyle='dashdot',linewidth=8)

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.plot(batsman['index'],batsman['V Kohli'],color='black',linestyle='dashdot',linewidth=3,marker='D',markersize=10,label='Virat')
plt.plot(batsman['index'],batsman['RG Sharma'],color='green',linestyle='dashdot',linewidth=8,label="Rohit")

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.legend()

price = [48000,54000,57000,49000,47000,45000000]
year = [2015,2016,2017,2018,2019,2020]

plt.plot(year,price)

price = [48000,54000,57000,49000,47000,45000000]
year = [2015,2016,2017,2018,2019,2020]

plt.plot(year,price)

plt.ylim=(0,50000)
plt.xlim(2010,2019)

plt.plot(batsman['index'],batsman['V Kohli'],color='black',linestyle='dashdot',linewidth=3,marker='D',markersize=10,label='Virat')
plt.plot(batsman['index'],batsman['RG Sharma'],color='green',linestyle='dashdot',linewidth=8,label="Rohit")

plt.title('Rohit Sh vs V Kohli career Comparision')
plt.xlabel('season')
plt.ylabel('runs')

plt.legend()
plt.grid()

"""**Scatter Plot**"""

x= np.linspace(-10,10,50)
y= 10*x +3+ np.random.randint(0,300,50)
y

plt.scatter(x,y)

df = pd.read_csv('batter.csv')
df.head(50)

plt.scatter(df['avg'],df['strike_rate'],color ='red', marker='+')
plt.title('Avg and Sr analysis of Top 50 Batsman')
plt.xlabel('Average')
plt.ylabel('SR')

"""SEABORN"""

tips = sns.load_dataset('tips')
tips

plt.scatter(tips['total_bill'],tips['tip'],s=tips['size']*20)

plt.plot(tips['total_bill'],tips['tip'], 'o')

"""**Bar Chart**"""

children =[23,30,78,51,33]
 colours = ['red','blue','green','yellow','pink']

plt.bar(colours,children,color='black')

plt.barh(colours,children,color='black')

df=pd.read_csv('/content/batsman_season_record.csv')
df

plt.bar(df['batsman'],df['2015'],width=0.1)

"""**Histogram**"""

data=[32,45,56,10,15,27,61]
plt.hist(data,bins=[10,25,40,55,70])

df=pd.read_csv('/content/vk.csv')
df

plt.hist(df['batsman_runs'],bins=[0,10,20,30,40,50,60,70,80,90])

"""**pie chart**"""

data=[23,45,67,78 ,98,100]
subjects=('sanskrit','hindi','history','geopolitics','maths','cs funda')
plt.pie(data,labels=subjects)

